quarkus.otel.exporter.otlp.protocol=http/protobuf
quarkus.application.name=orderservice 
quarkus.http.non-application-root-path=/
quarkus.otel.exporter.otlp.endpoint=http://localhost:4318
quarkus.rest-client.books-api.url=http://bookservice:8080
quarkus.rest-client.books-api.scope=jakarta.inject.Singleton
quarkus.tls.trust-all=true
